name: Build for Windows
on:
  workflow_dispatch:
    inputs:
      vs_arch:
        description: 'Target architecture (x64, x86, etc)'
        required: true
        default: 'x64'
      vs_toolset:
        description: 'Build toolset version (e.g. 16.4)'
        required: true
        default: '16.4'
      vs_version:
        description: 'Visual Studio version (e.g. 2019)'
        required: true
        default: '2019'
jobs:
  build:
    runs-on: windows-latest
    steps:
#      - name: Setup Node & Yarn
#        uses: mskelton/setup-yarn@v1
#        with:
#          node-version: '16.x'
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.x'
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: '${{ github.event.inputs.vs_arch }}'
          toolset: '${{ github.event.inputs.vs_toolset }}'
          spectre: false
          uwp: false
#      - name: 
#        run: npm config set msvs_version ${{ github.event.inputs.vs_version }}
      - name: Install the dependencies
        run: yarn
      - name: Compilation
        run: yarn compile
      - name: Packaging
        run: yarn gulp vscode-win32-x64-min