name: Build for Windows
on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Node & Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: '16.x'