name: Build for Windows
on:
  workflow_dispatch:
    inputs:
      pkg_version:
        description: 'Arbitrary release version'
        required: false
        default: '1.0.0'
      pkg_arch:
        description: 'Target package architecture (x64 or ia32)'
        required: true
        default: 'x64'
      vs_arch:
        description: 'Target MSVC architecture (x64, x86, etc)'
        required: true
        default: 'x64'
      node_version:
        description: 'Node.js version'
        required: true
        default: '16.x'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: '${{github.event.inputs.node_version}}'
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: '${{github.event.inputs.vs_arch}}'
          spectre: false
          uwp: false
      - name: Compilation
        run: yarn compile
      - name: Packaging
        run: yarn gulp vscode-win32-${{github.event.inputs.pkg_arch}}-min
      - name: Compression
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          path: '../VSCode-win32-${{github.event.inputs.pkg_arch}}/'
      - name: Release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          file: 'release.zip'
          tag: ${{github.event.inputs.pkg_version}}
          body: 'VSCodius version ${{github.event.inputs.pkg_version}} official release.'
          overwrite: true
          release_name: '${{github.event.inputs.pkg_version}}'
          asset_name: VSCodius-win32-${{github.event.inputs.pkg_arch}}-${{github.event.inputs.pkg_version}}.zip