name: Linux Unit Tests
on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node.js version'
        required: true
        default: '16.x'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '${{github.event.inputs.node_version}}'
      - name: Set up Yarn
        run: yarn
      - name: Compilation
        run: yarn compile
      - name: Testing
        run: ./scripts/test.sh > output.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: VSCodius-Linux-Testing-Logs.zip
          path: 'output.txt'