name: Linux Build Debug
on:
  workflow_dispatch:
    inputs:
      pkg_arch:
        description: 'Target package architecture (x64, ia32 or arm)'
        required: true
        default: 'x64'
      node_version:
        description: 'Node.js version'
        required: true
        default: '18'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '${{github.event.inputs.node_version}}'
      - name: Set up Yarn
        run: yarn
      - name: Packaging
        run: yarn gulp vscode-linux-${{github.event.inputs.pkg_arch}}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: VSCodius-Linux-${{github.event.inputs.pkg_arch}}-Debug
          path: '~/work/${{github.event.repository.name}}/VSCode-linux-${{github.event.inputs.pkg_arch}}'
          if-no-files-found: error