name: Linux Build Release
on:
  workflow_dispatch:
    inputs:
      pkg_version:
        description: 'Arbitrary release version'
        required: false
        default: '1.0.0'
      pkg_arch:
        description: 'Target package architecture (x64, ia32 or arm)'
        required: true
        default: 'x64'
      node_version:
        description: 'Node.js version'
        required: true
        default: '20'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{github.event.inputs.node_version}}'
      - name: Installing libraries
        run: sudo apt update && sudo apt install build-essential libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3 fakeroot rpm
      - name: Installing node-gyp
        run: yarn global add node-gyp
      - name: Dependencies
        run: yarn
      - name: Packaging
        run: yarn gulp vscode-linux-${{github.event.inputs.pkg_arch}}-min
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VSCodius-Linux-${{github.event.inputs.pkg_arch}}-${{github.event.inputs.pkg_version}}-Release
          path: '~/work/${{github.event.repository.name}}/VSCode-linux-${{github.event.inputs.pkg_arch}}'
          overwrite: true
          compression-level: 9
          if-no-files-found: error
