name: Windows Build Debug
on:
  workflow_dispatch:
    inputs:
      pkg_arch:
        description: 'Target package architecture (x64)'
        required: true
        default: 'x64'
      vs_arch:
        description: 'Target MSVC architecture (x64, etc)'
        required: true
        default: 'x64'
      node_version:
        description: 'Node.js version'
        required: true
        default: '20'
      patch_resources:
        description: 'Patch Win32 resources after build'
        type: boolean
        required: true
        default: false
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{github.event.inputs.node_version}}'
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Installing Yarn
        run: npm install -g yarn
      - name: Installing node-gyp
        run: yarn global add node-gyp
      - name: Dependencies
        run: yarn
      - name: Packaging
        run: yarn gulp vscode-win32-${{github.event.inputs.pkg_arch}}
      - name: Patch resources
        if: ${{github.event.inputs.patch_resources == 'true'}}
        run: node build\win32-resources-patch ..\VSCode-win32-${{github.event.inputs.pkg_arch}}/VSCodius.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VSCodius-Win32-${{github.event.inputs.pkg_arch}}-Debug
          path: 'D:\a\${{github.event.repository.name}}\VSCode-win32-${{github.event.inputs.pkg_arch}}'
          overwrite: true
          compression-level: 9
          if-no-files-found: error
